# Generated by Django 4.2.7 on 2023-11-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_answer_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerlike',
            name='value',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionlike',
            name='value',
            field=models.SmallIntegerField(default=0),
        ),
    ]
